### ISSUE TITLE
Is it possible to set(use) another type (eventually private) of repo?

### ISSUE THREAD

**Issue by kberov** [doy/dist-zilla-pluginbundle-doy#5]
I am new to Dist::Zilla but need to work on a project which uses Dist::Zilla::PluginBundle::DOY
In the dist.ini file it is possible to set `repository = github`. Other expected value is 'gitmo'. I would like to be able to use 'myprivatesitereponamehere'. 
In addition what would be the syntax to set 

``` perl
qw(repository.type repository.url repository.web bugtracker.web bugtracker.mailto homepage
```

about which I see warnings on the command line:

``` perl
 warn "*** resources.$metaresource is not configured! This needs to be fixed! ***"
```

The documentation does not mention anything about it.
Should I assume it from somewhere, or need knowledge from any other plugin.
Thanks in advance

**Comment by doy** [comment]
You can just leave `repository` unset, and specify the individual pieces of data individually:

```
repository_type = git
repository_url = git://example.com/my-repo.git
repository_web = https://example.com/my-repo
bugtracker_web = https://example.com/my-repo/issues
bugtracker_mailto = me+my-repo@example.com
```

The `repository` key is just a shorthand for configuring repositories for my personal setup.
